Added no animation
bodyflex/react-native-simple-modal pull request #19
Opened 2017-01-11 04:47 UTC by Nadeermalangadan

Added no animation if animationDuration is 0

2017-01-11 15:59 UTC, httnn requested changes

2017-01-11 15:59 UTC, bodyflex commented on index.js
> +      }
let's keep the style coherent and nice:
* space after `if` and before `(`
* spaces on both sides of `===`
* space before `{` and after `}`
* space on both sides of `?` and `:` in a ternary expression

sorry that there are no contribution guidelines, I should probably add some! :)

2017-01-11 15:59 UTC, bodyflex commented on index.js
> +         }else {
same here!

2017-01-12 06:53 UTC, nadeermalangadan reviewed
code formatted

2017-01-16 08:37 UTC, bodyflex commented
almost there, please still always use `{` and `}` with if statements even if they are only one line!

2017-01-19 09:56 UTC, Nadeermalangadan commented
update Pull request

2017-03-14 19:29 UTC, httnn approved these changes

2017-03-14 19:29 UTC, merged